[parity]
chain = "chain-spec.json"
base_path = "parity1"
[network]
port = 30303
# bootnodes = []
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8450
[account]
password = ["node1.pwd"]
[mining]
engine_signer = "0x58362c93194bf6c3829e80cfe06c03fd816363f4"
reseal_on_txs = "none"
force_sealing = true
[footprint]
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"
# Enables Fat DB
fat_db = "on"