[parity]
chain = "chain-spec.json"
base_path = "parity1"
[network]
port = 30303
# bootnodes = []
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8450
[account]
# password = ["node1.pwd"]
[mining]
# engine_signer = "0x51ec4ba053d69372aa2d4d79d85196eb25ca7053"
reseal_on_txs = "none"
force_sealing = true
[footprint]
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"
# Enables Fat DB
fat_db = "on"