[parity]
chain = "chain-spec.json"
base_path = "parity3"
[network]
port = 30303
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8450
[ipc]
disable = true
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00a94ac799442fb13de8302026fd03068ba6a428"
reseal_on_txs = "none"
[footprint]
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"
# Enables Fat DB
fat_db = "on"