[parity]
chain = "chain-spec.json"
base_path = "parity0"
[network]
port = 30303
# bootnodes = []
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8450
[account]
password = ["node0.pwd"]
[mining]
engine_signer = "0x6b2777e345c766c66e686ffbaa83aab4849b3ae4"
reseal_on_txs = "none"
force_sealing = true
[footprint]
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"
# Enables Fat DB
fat_db = "on"